


export const translations = {
      'es': {
          'nav.home': 'INICIO',
          'nav.solutions': 'SOLUCIONES',
          'nav.approach': 'ENFOQUE',
          'nav.blog': 'BLOG',
          'nav.faq': 'PREGUNTAS FRECUENTES',
          'nav.contact': 'CONTACTO',
          'nav.search-title': 'Buscar',
          'nav.call-title': 'Llamar',
          'menu.toggle.open': 'Abrir menú',
          'menu.toggle.close': 'Cerrar menú',
          'home.hero-heading.part1': 'Ofrece un servicio al cliente increíble',
          'home.hero-heading.part2': 'sin contratar un equipo',
          'home.hero-subheading': 'Para pequeñas empresas: clínicas dentales, gimnasios, bienes raíces, spas y salones. Nuestros agentes de voz y chat responden 24/7, califican clientes potenciales y agendan citas por ti',
          'home.book-call': 'Agenda una videollamada',
          'home.explore-solutions': 'Explora nuestras soluciones',
          'home.solutions-heading.part1': 'Nuestras',
          'home.solutions-heading.part2': 'Soluciones',
          'home.iris-heading': 'Iris',
          'home.iris-subheading': 'Soporte al cliente',
          'home.iris.feature1': 'Atención 24/7',
          'home.iris.feature2': 'Agenda citas fácilmente',
          'home.iris.feature3': 'Servicio amigable y cercano para tus clientes',
          'home.mike-heading': 'Mike',
          'home.mike-subheading': 'Ventas',
          'home.mike.feature1': 'Califica prospectos 24/7',
          'home.mike.feature2': 'Cierra ventas automáticamente',
          'home.mike.feature3': 'Vende día y noche sin interrupciones',
          'home.listen-demo': 'Escuchar demostración',
          'home.banner-heading.part1': 'Un servicio al cliente obsoleto',
          'home.banner-heading.part2': 'te está costando dinero',
          'home.banner-text-1': '¿Demasiados mensajes sin respuesta? ¿Calendario desordenado? ¿Clientes que no regresan?',
          'home.banner-text-2': 'Con IA confiable, respondes primero, reduces los costos generales y das soporte a tus clientes 24/7.',
          'features.heading.part1': 'Características',
          'features.heading.part2': 'Principales',
          'features.subheading': 'Descubre lo que nuestros agentes de IA pueden hacer por tu negocio.',
          'features.card-1-title': 'Entrenamiento Personalizado',
          'features.card-1-text': 'Entrenamos a los agentes con tu información: sitio web, documentos y FAQs para que respondan como un experto de tu equipo.',
          'features.card-2-title': 'Comunicación Omnicanal',
          'features.card-2-text': 'Interactúa con tus clientes a través de chat web, WhatsApp y llamadas de voz, todo gestionado por el mismo agente inteligente.',
          'features.card-3-title': 'Integración sin Esfuerzo',
          'features.card-3-text': 'Conectamos los agentes a tus sistemas existentes como CRMs, calendarios y bases de datos para automatizar flujos de trabajo.',
          'features.card-4-title': 'Disponibilidad 24/7',
          'features.card-4-text': 'Tu negocio nunca cierra. Atiende consultas, califica leads y agenda citas incluso fuera del horario laboral.',
          'features.card-5-title': 'Análisis e Informes',
          'features.card-5-text': 'Obtén información valiosa sobre las interacciones con tus clientes para mejorar tus servicios y estrategias de venta.',
          'features.card-6-title': 'Seguro y Confiable',
          'features.card-6-text': 'Construido con un enfoque en la seguridad de los datos y la fiabilidad, garantizando interacciones seguras y consistentes.',
          'solutions.heading.part1': 'Nuestras',
          'solutions.heading.part2': 'Soluciones',
          'solutions.consulting-title': 'Sesión estratégica en IA',
          'solutions.consulting-subtitle': 'Ha llegado el momento de optimizar tu negocio con IA.',
          'solutions.consulting-description-1': 'Sabes que la inteligencia artificial puede ayudarte… pero no sabes por dónde empezar',
          'solutions.consulting-description-2': 'y no tienes tiempo para probar sin resultados.',
          'solutions.consulting-what-we-do': 'Lo que hacemos contigo en esta sesión estratégica:',
          'solutions.consulting-benefit-1': 'Te escuchamos: analizamos tu negocio, retos y procesos',
          'solutions.consulting-benefit-2': 'Te guiamos: te explicamos cómo usar IA sin complicaciones ni tecnicismos',
          'solutions.consulting-benefit-3': 'Te entregamos claridad: una propuesta visual y simple para empezar con lo que más impacto tiene',
          'solutions.consulting-benefit-4': 'Te acompañamos: 4 horas para tomar decisiones con confianza',
          'solutions.consulting-exclusive': 'Exclusivo para PYMES, empresarios, autónomos y tomadores de decisión',
          'solutions.consulting-cta': 'Quiero saber mas',
          'solutions.card-1-title': 'Atención al Cliente IA 24/7',
          'solutions.card-1-text': 'Tu negocio, siempre abierto. Responde al instante, resuelve dudas y ofrece un soporte que fideliza a tus clientes.',
          'solutions.card-2-title': 'Gestor de Ventas IA 24/7',
          'solutions.card-2-text': 'Nunca pierdas una venta. Califica leads, agenda demos y nutre prospectos incluso mientras duermes.',
          'solutions.card-3-title': 'Gestor de Citas Inteligente',
          'solutions.card-3-text': 'Tu agenda, siempre llena y sin ausencias. Confirma, reagenda y envía recordatorios automáticamente.',
          'solutions.card-4-title': 'Community Manager IA',
          'solutions.card-4-text': 'Crece en redes sociales, sin esfuerzo. Genera contenido, responde comentarios y analiza tu audiencia.',
          'solutions.card-5-title': 'Especialista en Prospección IA',
          'solutions.card-5-text': 'Tu pipeline de ventas, siempre lleno. Identifica y califica leads de forma automática para que tu equipo se enfoque solo en cerrar.',
          'solutions.card-6-title': 'Especialista en Fidelización IA',
          'solutions.card-6-text': 'Recupera clientes inactivos y aumenta su valor a largo plazo con un seguimiento inteligente y proactivo.',
          'solutions.cta-button': '¡Quiero saber más!',
          'approach.heading.part1': 'Nuestro',
          'approach.heading.part2': 'Enfoque',
          'approach.subheading-main.part1': 'Personas primero, tecnología después.',
          'approach.subheading-main.part2': 'Diseñamos, entrenamos e integramos agentes de IA que realmente ayudan a tu negocio a crecer.',
          'approach.discovery-title': '1. Descubrimiento',
          'approach.discovery-text': 'Comprendemos tu operación, casos de uso y métricas objetivo. Mapeamos procesos y canales para encontrar el mayor impacto.',
          'approach.design-title': '2. Diseño y Entrenamiento',
          'approach.design-text': 'Definimos intenciones, tono y reglas. Entrenamos al agente con tu sitio web, bases de conocimiento y documentos.',
          'approach.integration-title': '3. Integración y Puesta en Marcha',
          'approach.integration-text': 'Conectamos con tus CRMs y canales (Web, WhatsApp, voz). Probamos, medimos e iteramos para asegurar el éxito.',
          'approach.tech-stack-title': 'Nuestra Pila Tecnológica',
          'approach.tech-stack-subtitle': 'Utilizamos tecnología de punta para crear soluciones robustas, escalables y seguras.',
          'approach.tech-1-title': 'IA y Machine Learning',
          'approach.tech-1-text': 'Modelos de lenguaje avanzados para conversaciones naturales y aprendizaje continuo.',
          'approach.tech-2-title': 'Procesamiento de Lenguaje Natural (NLP)',
          'approach.tech-2-text': 'Análisis de sentimiento, extracción de entidades y comprensión profunda del contexto.',
          'approach.tech-3-title': 'Integraciones y APIs',
          'approach.tech-3-text': 'Conexiones fluidas con tus herramientas existentes (CRM, Calendarios, Bases de Datos).',
          'approach.tech-4-title': 'Infraestructura en la Nube',
          'approach.tech-4-text': 'Alta disponibilidad y escalabilidad para manejar cualquier volumen de interacciones.',
          'approach.results-title': '¿El Resultado? Una Transformación Real',
          'approach.results-subtitle': 'No se trata de tecnología, se trata de lo que la tecnología hace por ti.',
          'approach.results-1-title': 'Más Ventas, Menos Fricción',
          'approach.results-1-text': 'Calificación de leads 24/7 y agendamiento automático para que tu equipo se enfoque en cerrar tratos.',
          'approach.results-2-title': 'Servicio al Cliente Excepcional',
          'approach.results-2-text': 'Respuestas instantáneas y precisas que aumentan la satisfacción y lealtad del cliente.',
          'approach.results-3-title': 'Menos Estrés Operativo',
          'approach.results-3-text': 'Automatización de tareas repetitivas que libera tu tiempo para la estrategia y el crecimiento.',
          'approach.results-4-title': 'Crecimiento Escalable',
          'approach.results-4-text': 'Maneja más interacciones sin aumentar los costos de personal. Crece de manera inteligente.',
          'approach.cta-button': 'Contáctanos para empezar',
          'blog.heading.part1': 'Nuestro',
          'blog.heading.part2': 'Blog',
          'blog.filter-all': 'Ver Todos',
          'blog.filter-automation': 'Automatización',
          'blog.filter-strategy': 'Estrategia',
          'blog.filter-sales': 'Ventas',
          'blog.filter-errors': 'Errores Comunes',
          'blog.filter-education': 'Educación',
          'blog.filter-inside-stories': 'Desde Adentro',
          'blog.no-posts': 'No hay publicaciones en esta categoría.',
          'blog.read-more': 'Leer más →',
          'blog.creation-date': 'Fecha de creación',
          'post.back-to-blog': '← Volver al blog',
          'post.author-prefix': 'Por',
          'post.not-found': 'Artículo no encontrado.',
          'post.load-error': 'Error al cargar el artículo.',
          'faq.heading.part1': 'Preguntas',
          'faq.heading.part2': 'Frecuentes',
          'faq.question-1-title': '¿Qué es la inteligencia artificial (IA) y cómo puede ayudar a mi negocio?',
          'faq.question-1-answer': 'La inteligencia artificial es una tecnología que permite a las máquinas aprender y tomar decisiones. Puede ayudarte a automatizar tareas, mejorar la atención al cliente, analizar datos y ahorrar tiempo y dinero.',
          'faq.question-2-title': '¿Es necesario saber programar para usar herramientas de IA?',
          'faq.question-2-answer': 'No. Hoy en día existen herramientas de IA sin necesidad de programación. Se llaman \'no-code\' y te permiten crear soluciones con interfaces visuales.',
          'faq.question-3-title': '¿Qué tareas puedo automatizar con IA en mi negocio?',
          'faq.question-3-answer': 'Puedes automatizar respuestas a clientes, envíos de email, creación de contenido, gestión de redes sociales, seguimiento de ventas y mucho más.',
          'faq.question-4-title': '¿Cómo empiezo a usar IA si no tengo experiencia?',
          'faq.question-4-answer': 'Empieza con herramientas simples como ChatGPT, Canva con IA o Google Sheets con automatizaciones. Luego puedes avanzar con plataformas como N8N o Make.',
          'faq.question-5-title': '¿La IA puede ayudarme a conseguir más clientes?',
          'faq.question-5-answer': 'Sí. Puedes usar IA para generar contenido atractivo, responder rápidamente a mensajes, analizar datos de tus seguidores y personalizar tus ofertas.',
          'faq.question-6-title': '¿Cuáles son los errores más comunes al usar IA en pequeños negocios?',
          'faq.question-6-answer': 'No tener un objetivo claro, usar herramientas complejas sin necesidad, o depender 100% de la IA sin revisar los resultados.',
          'faq.question-7-title': '¿La IA reemplaza a los trabajadores humanos?',
          'faq.question-7-answer': 'No necesariamente. La IA está diseñada para apoyar y complementar el trabajo humano, ayudando a que las personas se enfoquen en tareas más creativas y estratégicas.',
          'faq.question-8-title': '¿Qué herramientas de IA recomiendas para empezar?',
          'faq.question-8-answer': 'ChatGPT para textos, Canva para diseño, Pictory para videos, Tidio para chatbots, y N8N para automatizaciones.',
          'faq.question-9-title': '¿Cuánto cuesta implementar IA en un pequeño negocio?',
          'faq.question-9-answer': 'Depende de la herramienta. Muchas son gratuitas o tienen planes muy económicos. Lo importante es empezar poco a poco y elegir bien.',
          'faq.question-10-title': '¿Cómo se si mi negocio está listo para usar IA?',
          'faq.question-10-answer': 'Si tienes procesos repetitivos, clientes que atender, datos que analizar o contenido que crear, ya puedes empezar a usar IA para ahorrar tiempo.',
          'faq.question-11-title': '¿La IA es segura para mi información?',
          'faq.question-11-answer': 'Sí, si usas herramientas confiables. Siempre revisa las políticas de privacidad y evita compartir datos sensibles con sistemas automáticos.',
          'faq.question-12-title': '¿Puedo usar IA para crear contenido en redes sociales?',
          'faq.question-12-answer': 'Claro que sí. Puedes generar ideas, escribir textos, crear diseños y hasta programar publicaciones automáticamente.',
          'faq.question-13-title': '¿La IA funciona en español?',
          'faq.question-13-answer': 'Sí. La mayoría de herramientas de IA modernas entienden y generan contenido en español sin problemas.',
          'faq.question-14-title': '¿Puedo aprender a usar IA aunque no sea experto en tecnología?',
          'faq.question-14-answer': 'Totalmente. Hay cursos, tutoriales y comunidades que te ayudan paso a paso. Y muchas herramientas son fáciles e intuitivas.',
          'faq.question-15-title': '¿Tienen ejemplos de cómo otras emprendedoras han usado IA con éxito?',
          'faq.question-15-answer': 'Sí, puedes leer historias reales en nuestro blog \'Desde Adentro\', donde mostramos casos de pequnas empresas que usan IA para atraer clientes, ahorrar tiempo o reinventar su negocio.',
          'contact.heading.part1': 'Contáctanos',
          'contact.heading.part2': 'Ahora',
          'contact.subheading.part1': '¿Tienes alguna pregunta? Estamos aquí para ayudarte. Rellena el formulario o utiliza nuestras otras vías de contacto.',
          'contact.subheading.part2': 'Te responderemos lo antes posible.',
          'contact.other-ways.part1': 'Otras formas de',
          'contact.other-ways.part2': 'contactar',
          'contact.submit': 'Enviar Mensaje',
          'contact.call-us-title': 'Llámanos',
          'contact.call-us-subtitle': 'Estamos aquí para ayudarte',
          'contact.write-us': 'Escríbenos',
          'contact.schedule-title': 'Agenda',
          'contact.schedule-subtitle': 'Agenda una demostración',
          'contact.follow-us': 'Síguenos',
          'contact.form-name-label': 'Nombre completo',
          'contact.form-name-placeholder': 'Tu nombre',
          'contact.form-email-label': 'Correo electrónico',
          'contact.form-email-placeholder': 'tu@correo.com',
          'contact.form-phone-label': 'Teléfono (Opcional)',
          'contact.form-phone-placeholder': 'Tu número de teléfono',
          'contact.form-message-label': 'Mensaje',
          'contact.form-message-placeholder': '¿Cómo podemos ayudarte?',
          'contact.form-success-heading': '¡Mensaje Enviado!',
          'contact.form-success-text': 'Gracias por contactarnos. Nos pondremos en contacto contigo pronto.',
          'contact.form-sending': 'Enviando...',
          'footer.links-heading': 'Mapa del sitio',
          'footer.social-heading': 'Síguenos',
          'footer.newsletter-heading': 'Suscríbete al Newsletter',
          'footer.newsletter-placeholder': 'Ingresa tu email',
          'footer.newsletter-button': 'Suscribir',
          'footer.newsletter-subscribing': 'Suscribiendo...',
          'footer.newsletter-subscribed': '¡Suscrito!',
          'footer.email-label': 'Correo electrónico',
          'footer.rights-reserved': 'Todos los derechos reservados.',
          'footer.tagline': 'Impulsando tu negocio con el poder de la Inteligencia Artificial.',
          'footer.terms': 'Términos de Servicio',
          'footer.privacy': 'Política de Privacidad',
          'footer.cookies': 'Política de Cookies',
          'footer.version': 'Versión',
          'chat.typing': 'Iris está escribiendo',
          'chat.placeholder': 'Escribe tu mensaje...',
          'chat.input-label': 'Mensaje de chat',
          'chat.send-button-label': 'Enviar mensaje',
          'chat.welcome': '¡Hola! 👋 Soy Iris. ¿Cómo puedo ayudarte hoy?',
          'chat.error': 'Lo siento, el servicio de chat no está disponible en este momento por mantenimiento. Por favor, intenta de nuevo más tarde.',
          'chat.fetch-error': '¡Ups! No pudimos conectar con nuestro asistente. Parece haber un problema de red. Por favor, revisa tu conexión e inténtalo de nuevo.',
          'chat.server-error': 'Lo siento, ocurrió un problema al comunicarnos con nuestro asistente. Por favor, inténtalo de nuevo en unos momentos.',
          'chat.not-found-error': 'Lo siento, parece que nuestro asistente no está disponible en este momento (error 404). Por favor, avisa a nuestro equipo técnico.',
          'chat.timeout-error': 'La respuesta del asistente está tardando más de lo esperado. Por favor, intenta de nuevo.',
          'koalendar.link': 'https://koalendar.com/e/ailabmind-es',
          'consent.title': 'Usamos cookies',
          'consent.description': 'Este sitio web utiliza cookies para mejorar su experiencia de usuario. Al utilizar nuestro sitio web, usted acepta todas las cookies de acuerdo con nuestra',
          'consent.cookie-policy-link': 'Política de Cookies.',
          'consent.settings': 'Ajustes de cookies',
          'consent.reject-all': 'Rechazar Todo',
          'consent.accept-all': 'Aceptar Todo',
          'consent.newsletter-label': 'Suscribirme al boletín',
          'consent.agree-marketing': 'Acepto recibir comunicaciones de marketing. He leído y acepto la ',
          'consent.privacy-policy': 'Política de Privacidad',
          'privacy-center.title': 'Centro de Preferencias de Privacidad',
          'privacy-center.description': 'Cuando visita cualquier sitio web, éste puede almacenar o recuperar información en su navegador, principalmente en forma de cookies. Esta información puede ser sobre usted, sus preferencias o su dispositivo y se utiliza para mejorar su experiencia de navegación, ofrecer anuncios o contenidos personalizados y analizar nuestro tráfico. Como respetamos su derecho a la privacidad, puede optar por no permitir algunos tipos de cookies. Haga clic en los diferentes encabezados de categoría para obtener más información y cambiar nuestra configuración predeterminada.',
          'privacy-center.necessary.title': 'Cookies Estrictamente Necesarias',
          'privacy-center.necessary.description': 'Estas cookies son necesarias para que el sitio web funcione y no pueden ser desactivadas en nuestros sistemas. Usualmente están configuradas para responder a acciones hechas por usted para recibir servicios, tales como ajustar sus preferencias de privacidad, iniciar sesión en el sitio, o llenar formularios.',
          'privacy-center.performance.title': 'Cookies de Rendimiento',
          'privacy-center.performance.description': 'Estas cookies nos permiten contar las visitas y fuentes de circulación para poder medir y mejorar el desempeño de nuestro sitio. Nos ayudan a saber qué páginas son las más o menos populares, y ver cuántas personas visitan el sitio.',
          'privacy-center.functional.title': 'Cookies Funcionales',
          'privacy-center.functional.description': 'Estas cookies permiten que el sitio ofrezca una mejor funcionalidad y personalización. Pueden ser establecidas por nosotros o por terceras partes cuyos servicios hemos agregado a nuestras páginas.',
          'privacy-center.targeting.title': 'Cookies de Segmentación',
          'privacy-center.targeting.description': 'Estas cookies pueden estar en todo el sitio web, colocadas por nuestros socios publicitarios. Estos negocios pueden utilizarlas para crear un perfil de sus intereses y mostrarle anuncios relevantes en otros sitios.',
          'privacy-center.save': 'Guardar Mis Preferencias',
          'voice.connecting': 'Conectando...',
          'voice.call-initiated': 'Llamada iniciada. Te llamaremos en breve.',
          'voice.call-failed': 'Error al conectar. Inténtalo de nuevo.',
          'voice.modal-title': 'Asistente de Voz AI',
          'voice.status-initializing': 'Iniciando...',
          'voice.status-connecting': 'Conectando...',
          'voice.status-listening': 'Escuchando...',
          'voice.status-speaking': 'Asistente hablando...',
          'voice.status-processing': 'Procesando tu respuesta...',
          'voice.status-error': 'Error de conexión. Inténtalo de nuevo.',
          'voice.status-ended': 'Llamada finalizada',
          'voice.end-call': 'Finalizar Llamada',
          'voice.mic-permission': 'Necesitamos acceso a tu micrófono para continuar. Por favor, actívalo en tu navegador.',
          'legal.terms-link': './assets/legal/terms-es.html',
          'legal.privacy-link': './assets/legal/privacy-es.html',
          'legal.cookies-link': './assets/legal/cookies-es.html'
      },
      'en': {
          'nav.home': 'HOME',
          'nav.solutions': 'SOLUTIONS',
          'nav.approach': 'APPROACH',
          'nav.blog': 'BLOG',
          'nav.faq': 'FAQ',
          'nav.contact': 'CONTACT',
          'nav.search-title': 'Search',
          'nav.call-title': 'Call',
          'menu.toggle.open': 'Open menu',
          'menu.toggle.close': 'Close menu',
          'home.hero-heading.part1': 'Deliver amazing customer service',
          'home.hero-heading.part2': 'without hiring a team',
          'home.hero-subheading': 'For small businesses: dental clinics, gyms, real estate, spas, and salons. Our voice and chat agents answer 24/7, qualify leads, and book appointments for you.',
          'home.book-call': 'Book a video call',
          'home.explore-solutions': 'Explore our solutions',
          'home.solutions-heading.part1': 'Our',
          'home.solutions-heading.part2': 'Solutions',
          'home.iris-heading': 'Iris',
          'home.iris-subheading': 'Customer Support',
          'home.iris.feature1': '24/7 Support',
          'home.iris.feature2': 'Schedule appointments easily',
          'home.iris.feature3': 'Friendly and approachable service for your customers',
          'home.mike-heading': 'Mike',
          'home.mike-subheading': 'Sales',
          'home.mike.feature1': 'Qualifies leads 24/7',
          'home.mike.feature2': 'Closes sales automatically',
          'home.mike.feature3': 'Sells day and night without interruptions',
          'home.listen-demo': 'Listen to demo',
          'home.banner-heading.part1': 'Outdated customer service',
          'home.banner-heading.part2': 'is costing you money',
          'home.banner-text-1': 'Too many unanswered messages? Messy calendar? Customers not coming back?',
          'home.banner-text-2': 'With reliable AI, you respond first, reduce overhead costs, and support your customers 24/7.',
          'features.heading.part1': 'Main',
          'features.heading.part2': 'Features',
          'features.subheading': 'Discover what our AI agents can do for your business.',
          'features.card-1-title': 'Custom Training',
          'features.card-1-text': 'We train agents with your information: website, documents, and FAQs, so they respond like an expert on your team.',
          'features.card-2-title': 'Omnichannel Communication',
          'features.card-2-text': 'Interact with your customers via web chat, WhatsApp, and voice calls, all managed by the same intelligent agent.',
          'features.card-3-title': 'Effortless Integration',
          'features.card-3-text': 'We connect agents to your existing systems like CRMs, calendars, and databases to automate workflows.',
          'features.card-4-title': '24/7 Availability',
          'features.card-4-text': 'Your business never closes. Handle inquiries, qualify leads, and schedule appointments even after business hours.',
          'features.card-5-title': 'Analytics & Reports',
          'features.card-5-text': 'Get valuable insights from customer interactions to improve your services and sales strategies.',
          'features.card-6-title': 'Secure & Reliable',
          'features.card-6-text': 'Built with a focus on data security and reliability, ensuring safe and consistent interactions.',
          'solutions.heading.part1': 'Our',
          'solutions.heading.part2': 'Solutions',
          'solutions.consulting-title': 'Strategic AI Session',
          'solutions.consulting-subtitle': 'The time has come to optimize your business with AI.',
          'solutions.consulting-description-1': 'You know artificial intelligence can help you… but you don\'t know where to start',
          'solutions.consulting-description-2': 'and you don\'t have time to test without results.',
          'solutions.consulting-what-we-do': 'What we do with you in this strategic session:',
          'solutions.consulting-benefit-1': 'We listen: we analyze your business, challenges, and processes',
          'solutions.consulting-benefit-2': 'We guide you: we explain how to use AI without complications or technical jargon',
          'solutions.consulting-benefit-3': 'We deliver clarity: a visual and simple proposal to start with what has the most impact',
          'solutions.consulting-benefit-4': 'We accompany you: 4 hours to make decisions with confidence',
          'solutions.consulting-exclusive': 'Exclusive for SMEs, entrepreneurs, freelancers, and decision-makers',
          'solutions.consulting-cta': 'I want to know more',
          'solutions.card-1-title': '24/7 AI Customer Support',
          'solutions.card-1-text': 'Your business, always open. Instantly answer questions, resolve issues, and provide support that builds customer loyalty.',
          'solutions.card-2-title': '24/7 AI Sales Manager',
          'solutions.card-2-text': 'Never miss a sale again. Qualify leads, book demos, and nurture prospects even while you sleep.',
          'solutions.card-3-title': 'Intelligent Appointment Manager',
          'solutions.card-3-text': 'Your calendar, always full and no-show free. Automatically confirm, reschedule, and send smart reminders.',
          'solutions.card-4-title': 'AI Community Manager',
          'solutions.card-4-text': 'Grow your social media, effortlessly. Generate content, respond to comments, and analyze your audience.',
          'solutions.card-5-title': 'AI Prospecting Specialist',
          'solutions.card-5-text': 'Your sales pipeline, always full. Automatically identifies and qualifies leads so your team can focus only on closing deals.',
          'solutions.card-6-title': 'AI Loyalty Specialist',
          'solutions.card-6-text': 'Recover lost customers and increase their lifetime value with smart, proactive follow-ups.',
          'solutions.cta-button': 'I want to know more!',
          'approach.heading.part1': 'Our',
          'approach.heading.part2': 'Approach',
          'approach.subheading-main.part1': 'People first, technology second.',
          'approach.subheading-main.part2': 'We design, train, and integrate AI agents that truly help your business grow.',
          'approach.discovery-title': '1. Discovery',
          'approach.discovery-text': 'We understand your operations, use cases, and target metrics. We map processes and channels to find the greatest impact.',
          'approach.design-title': '2. Design & Training',
          'approach.design-text': 'We define intentions, tone, and rules. We train the agent with your website, knowledge bases, and documents.',
          'approach.integration-title': '3. Integration & Launch',
          'approach.integration-text': 'We connect with your CRMs and channels (Web, WhatsApp, voice). We test, measure, and iterate to ensure success.',
          'approach.tech-stack-title': 'Our Tech Stack',
          'approach.tech-stack-subtitle': 'We use cutting-edge technology to build robust, scalable, and secure solutions.',
          'approach.tech-1-title': 'AI & Machine Learning',
          'approach.tech-1-text': 'Advanced language models for natural conversations and continuous learning.',
          'approach.tech-2-title': 'Natural Language Processing (NLP)',
          'approach.tech-2-text': 'Sentiment analysis, entity extraction, and deep contextual understanding.',
          'approach.tech-3-title': 'Integrations & APIs',
          'approach.tech-3-text': 'Seamless connections with your existing tools (CRM, Calendars, Databases).',
          'approach.tech-4-title': 'Cloud Infrastructure',
          'approach.tech-4-text': 'High availability and scalability to handle any volume of interactions.',
          'approach.results-title': 'The Result? A Real Transformation',
          'approach.results-subtitle': 'It\'s not about technology, it\'s about what technology does for you.',
          'approach.results-1-title': 'More Sales, Less Friction',
          'approach.results-1-text': '24/7 lead qualification and automatic scheduling so your team can focus on closing deals.',
          'approach.results-2-title': 'Exceptional Customer Service',
          'approach.results-2-text': 'Instant, accurate answers that increase customer satisfaction and loyalty.',
          'approach.results-3-title': 'Less Operational Stress',
          'approach.results-3-text': 'Automation of repetitive tasks that frees up your time for strategy and growth.',
          'approach.results-4-title': 'Scalable Growth',
          'approach.results-4-text': 'Handle more interactions without increasing personnel costs. Grow smarter.',
          'approach.cta-button': 'Contact us to get started',
          'blog.heading.part1': 'Our',
          'blog.heading.part2': 'Blog',
          'blog.filter-all': 'View All',
          'blog.filter-automation': 'Automation',
          'blog.filter-strategy': 'Strategy',
          'blog.filter-sales': 'Sales',
          'blog.filter-errors': 'Common Errors',
          'blog.filter-education': 'Education',
          'blog.filter-inside-stories': 'Inside Stories',
          'blog.no-posts': 'There are no posts in this category.',
          'blog.read-more': 'Read more →',
          'blog.creation-date': 'Creation date',
          'post.back-to-blog': '← Back to blog',
          'post.author-prefix': 'By',
          'post.not-found': 'Article not found.',
          'post.load-error': 'Error loading article.',
          'faq.heading.part1': 'Frequently Asked',
          'faq.heading.part2': 'Questions',
          'faq.question-1-title': 'What is artificial intelligence (AI) and how can it help my business?',
          'faq.question-1-answer': 'Artificial intelligence is a technology that allows machines to learn and make decisions. It can help you automate tasks, improve customer service, analyze data, and save time and money.',
          'faq.question-2-title': 'Do I need to know how to code to use AI tools?',
          'faq.question-2-answer': 'No. Nowadays, there are AI tools that do not require programming. They are called \'no-code\' and allow you to create solutions with visual interfaces.',
          'faq.question-3-title': 'What tasks can I automate with AI in my business?',
          'faq.question-3-answer': 'You can automate customer responses, email sending, content creation, social media management, sales tracking, and much more.',
          'faq.question-4-title': 'How do I start using AI if I have no experience?',
          'faq.question-4-answer': 'Start with simple tools like ChatGPT, Canva with AI, or Google Sheets with automations. Then you can move on to platforms like N8N or Make.',
          'faq.question-5-title': 'Can AI help me get more customers?',
          'faq.question-5-answer': 'Yes. You can use AI to generate engaging content, respond quickly to messages, analyze your followers\' data, and personalize your offers.',
          'faq.question-6-title': 'What are the most common mistakes when using AI in small businesses?',
          'faq.question-6-answer': 'Not having a clear objective, using complex tools unnecessarily, or relying 100% on AI without reviewing the results.',
          'faq.question-7-title': 'Does AI replace human workers?',
          'faq.question-7-answer': 'Not necessarily. AI is designed to support and complement human work, helping people focus on more creative and strategic tasks.',
          'faq.question-8-title': 'What AI tools do you recommend for beginners?',
          'faq.question-8-answer': 'ChatGPT for texts, Canva for design, Pictory for videos, Tidio for chatbots, and N8N for automations.',
          'faq.question-9-title': 'How much does it cost to implement AI in a small business?',
          'faq.question-9-answer': 'It depends on the tool. Many are free or have very affordable plans. The important thing is to start small and choose wisely.',
          'faq.question-10-title': 'How do I know if my business is ready to use AI?',
          'faq.question-10-answer': 'If you have repetitive processes, customers to attend to, data to analyze, or content to create, you can already start using AI to save time.',
          'faq.question-11-title': 'Is AI safe for my information?',
          'faq.question-11-answer': 'Yes, if you use reliable tools. Always check the privacy policies and avoid sharing sensitive data with automated systems.',
          'faq.question-12-title': 'Can I use AI to create content for social media?',
          'faq.question-12-answer': 'Of course. You can generate ideas, write texts, create designs, and even schedule posts automatically.',
          'faq.question-13-title': 'Does AI work in English?',
          'faq.question-13-answer': 'Yes. Most modern AI tools understand and generate content in English without any issues.',
          'faq.question-14-title': 'Can I learn to use AI even if I\'m not a tech expert?',
          'faq.question-14-answer': 'Absolutely. There are courses, tutorials, and communities that help you step by step. And many tools are easy and intuitive.',
          'faq.question-15-title': 'Do you have examples of how other entrepreneurs have successfully used AI?',
          'faq.question-15-answer': 'Yes, you can read real stories on our \'Inside Stories\' blog, where we showcase cases of small businesses using AI to attract customers, save time, or reinvent their business.',
          'contact.heading.part1': 'Contact',
          'contact.heading.part2': 'Us',
          'contact.subheading.part1': 'Have a question? We\'re here to help. Fill out the form or use our other contact methods.',
          'contact.subheading.part2': 'We\'ll get back to you as soon as possible.',
          'contact.other-ways.part1': 'Other ways to',
          'contact.other-ways.part2': 'contact',
          'contact.submit': 'Send Message',
          'contact.call-us-title': 'Call Us',
          'contact.call-us-subtitle': 'We are here to help.',
          'contact.write-us': 'Email Us',
          'contact.schedule-title': 'Schedule',
          'contact.schedule-subtitle': 'Book a demo',
          'contact.follow-us': 'Follow Us',
          'contact.form-name-label': 'Full name',
          'contact.form-name-placeholder': 'Your name',
          'contact.form-email-label': 'Email',
          'contact.form-email-placeholder': 'you@email.com',
          'contact.form-phone-label': 'Phone (Optional)',
          'contact.form-phone-placeholder': 'Your phone number',
          'contact.form-message-label': 'Message',
          'contact.form-message-placeholder': 'How can we help you?',
          'contact.form-success-heading': 'Message Sent!',
          'contact.form-success-text': 'Thanks for getting in touch. We will contact you shortly.',
          'contact.form-sending': 'Sending...',
          'footer.links-heading': 'Sitemap',
          'footer.social-heading': 'Follow Us',
          'footer.newsletter-heading': 'Subscribe to Newsletter',
          'footer.newsletter-placeholder': 'Enter your email',
          'footer.newsletter-button': 'Subscribe',
          'footer.newsletter-subscribing': 'Subscribing...',
          'footer.newsletter-subscribed': 'Subscribed!',
          'footer.email-label': 'Email',
          'footer.rights-reserved': 'All rights reserved.',
          'footer.tagline': 'Powering your business with the power of Artificial Intelligence.',
          'footer.terms': 'Terms of Service',
          'footer.privacy': 'Privacy Policy',
          'footer.cookies': 'Cookie Policy',
          'footer.version': 'Version',
          'chat.typing': 'Iris is typing',
          'chat.placeholder': 'Type your message...',
          'chat.input-label': 'Chat message',
          'chat.send-button-label': 'Send message',
          'chat.welcome': 'Hi! 👋 I\'m Iris. How can I help you today?',
          'chat.error': 'I\'m sorry, the chat service is currently unavailable for maintenance. Please try again later.',
          'chat.fetch-error': 'Oops! We couldn\'t connect to our assistant. It seems there\'s a network issue. Please check your connection and try again.',
          'chat.server-error': 'I\'m sorry, there was a problem communicating with our assistant. Please try again in a few moments.',
          'chat.not-found-error': 'I\'m sorry, it seems our assistant is currently unavailable (error 404). Please notify our technical team.',
          'chat.timeout-error': 'The assistant\'s response is taking longer than expected. Please try again.',
          'koalendar.link': 'https://koalendar.com/e/ailabmind-en',
          'consent.title': 'We use cookies',
          'consent.description': 'This website uses cookies to improve your user experience. By using our website, you consent to all cookies in accordance with our',
          'consent.cookie-policy-link': 'Cookie Policy.',
          'consent.settings': 'Cookie settings',
          'consent.reject-all': 'Reject All',
          'consent.accept-all': 'Accept All',
          'consent.newsletter-label': 'Subscribe to newsletter',
          'consent.agree-marketing': 'I agree to receive marketing communications. I have read and accept the ',
          'consent.privacy-policy': 'Privacy Policy',
          'privacy-center.title': 'Privacy Preference Center',
          'privacy-center.description': 'When you visit any website, it may store or retrieve information on your browser, mostly in the form of cookies. This information might be about you, your preferences or your device and we use it to enhance your browsing experience, serve personalised ads or content, and analyse our traffic. Because we respect your right to privacy, you can choose not to allow some types of cookies. Click on the different category headings to find out more and change our default settings.',
          'privacy-center.necessary.title': 'Strictly Necessary Cookies',
          'privacy-center.necessary.description': 'These cookies are necessary for the website to function and cannot be switched off in our systems. They are usually only set in response to actions made you which amount to a request for services, such as setting your privacy preferences, logging in or filling in forms.',
          'privacy-center.performance.title': 'Performance Cookies',
          'privacy-center.performance.description': 'These cookies allow us to count visits and traffic sources so we can measure and improve the performance of our site. They help us to know which pages are the most and least popular and see how visitors move around the site.',
          'privacy-center.functional.title': 'Functional Cookies',
          'privacy-center.functional.description': 'These cookies enable the website to provide enhanced functionality and personalisation. They may be set by us or by third party providers whose services we have added to our pages.',
          'privacy-center.targeting.title': 'Targeting Cookies',
          'privacy-center.targeting.description': 'These cookies may be set through our site by our advertising partners. They may be used by those companies to build a profile of your interests and show you relevant adverts on other sites.',
          'privacy-center.save': 'Save My Preferences',
          'voice.connecting': 'Connecting...',
          'voice.call-initiated': 'Call initiated. We will call you shortly.',
          'voice.call-failed': 'Failed to connect. Please try again.',
          'voice.modal-title': 'AI Voice Assistant',
          'voice.status-initializing': 'Initializing...',
          'voice.status-connecting': 'Connecting...',
          'voice.status-listening': 'Listening...',
          'voice.status-speaking': 'Assistant speaking...',
          'voice.status-processing': 'Processing your response...',
          'voice.status-error': 'Connection error. Please try again.',
          'voice.status-ended': 'Call Ended',
          'voice.end-call': 'End Call',
          'voice.mic-permission': 'We need microphone access to continue. Please enable it in your browser.',
          'legal.terms-link': './assets/legal/terms-en.html',
          'legal.privacy-link': './assets/legal/privacy-en.html',
          'legal.cookies-link': './assets/legal/cookies-en.html'
      }
};

export let currentLang = 'es';

function updateDOM() {
    document.querySelectorAll('[data-lang-key]').forEach(element => {
        const key = element.getAttribute('data-lang-key');
        if (translations[currentLang] && translations[currentLang][key]) {
            element.textContent = translations[currentLang][key];
        }
    });
    
    document.querySelectorAll('[data-lang-title-key]').forEach(element => {
        const key = element.getAttribute('data-lang-title-key');
        if (translations[currentLang] && translations[currentLang][key]) {
            element.title = translations[currentLang][key];
        }
    });

    document.querySelectorAll('[data-lang-placeholder-key]').forEach(element => {
      const key = element.getAttribute('data-lang-placeholder-key');
      if (translations[currentLang] && translations[currentLang][key]) {
          element.placeholder = translations[currentLang][key];
      }
    });

    document.querySelectorAll('[data-lang-href-key]').forEach(element => {
      const key = element.getAttribute('data-lang-href-key');
      if(translations[currentLang][key]) {
        element.href = translations[currentLang][key];
      }
    });

    document.querySelectorAll('[data-lang-aria-label-key]').forEach(element => {
      const key = element.getAttribute('data-lang-aria-label-key');
      if(translations[currentLang][key]) {
          element.setAttribute('aria-label', translations[currentLang][key]);
      }
    });
    
    const consentDesc = document.querySelector('[data-lang-key="consent.description"]');
    if (consentDesc) {
      consentDesc.textContent = translations[currentLang]['consent.description'] + ' ';
      const link = consentDesc.nextElementSibling;
      if (link && link.dataset.langKey === 'consent.cookie-policy-link') {
          link.textContent = translations[currentLang]['consent.cookie-policy-link'];
      }
    }

    document.getElementById('lang-toggle-text').textContent = currentLang === 'es' ? 'EN' : 'ES';

    // Dispatch event to notify other modules of the language change
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang: currentLang } }));
}

export function getTranslation(key) {
    return translations[currentLang][key] || key;
}

export function setLanguage(lang, force = false) {
    if (!translations[lang] || (currentLang === lang && !force)) return;
    currentLang = lang;
    document.documentElement.lang = lang;
    updateDOM();
}

export function initLanguage() {
    const langToggleButton = document.getElementById('lang-toggle');
    langToggleButton.addEventListener('click', () => {
        const newLang = currentLang === 'es' ? 'en' : 'es';
        setLanguage(newLang);
    });

    const userLang = navigator.language.split('-')[0];
    const initialLang = ['es', 'en'].includes(userLang) ? userLang : 'es';
    setLanguage(initialLang, true);
}